kumuluzee:
  server:
    http:
      port: 8083
    context-path: /
  logs:
    level: INFO
  dev:
    scan-interval: 5
  datasource:
    mongodb:
      connectionString: ${MONGO_URI}
      database: "users"
  security:
    providers:
      jwt:
        key: ${JWT_SECRET}
        algorithm: HS256
        issuer: "common-service"
        audience: "finance-frontend"
        claims:
          roles: "roles"