kumuluzee:
  server:
    http:
      port: 8083
    context-path: /
  logs:
    level: INFO
  dev:
    scan-interval: 5
  datasource:
    mongodb:
      connectionString: "mongodb://localhost:27017"
      database: "users"
  security:
    providers:
      jwt:
        key: "aU0Gx6LJbYukM9DJmcFZjx0q3wx+TnpRkmRu2F7rx3Y="
        algorithm: HS256
        issuer: "common-service"
        audience: "finance-frontend"
        claims:
          roles: "roles"