kumuluzee:
  server:
    http:
      port: 8080
    context-path: /
    base-url: http://localhost:8080
  logs:
    level: INFO
  dev:
    scan-interval: 5
  datasource:
    mongodb:
      connectionString:  ${MONGO_URI}
      database: "financeApp"
  security:
    providers:
      jwt:
        key:  ${JWT_SECRET}
        algorithm: HS256
        issuer: "user-service"
        audience: "finance-frontend"
        claims:
          roles: "roles"

  openapi:
    enabled: true
    servers:
      - url: http://localhost:8080
    info:
      title: "API Documentation"
      version: "1.0"
      description: "Opis REST API endpointov za uporabniško mikrostoritev"
  cors:
    enabled: true
    allow-origins:
      - http://localhost:4200
    allow-methods:
      - GET
      - POST
      - PUT
      - DELETE
    allow-headers:
      - Content-Type
      - Authorization
      - Cookie
    allow-credentials: true
