kumuluzee:
  server:
    http:
      port: 8080
    context-path: /
  logs:
    level: INFO
  dev:
    scan-interval: 5
  datasource:
    mongodb:
      connectionString: "mongodb://mongodb:27017"
      database: "financeApp"
  security:
    providers:
      jwt:
        key: "aU0Gx6LJbYukM9DJmcFZjx0q3wx+TnpRkmRu2F7rx3Y="
        algorithm: HS256
        issuer: "user-service"
        audience: "finance-frontend"
        claims:
          roles: "roles"
  cors:
    enabled: true
    allow-origins:
      - http://localhost:4200
    allow-methods:
      - GET
      - POST
      - PUT
      - DELETE
    allow-headers:
      - Content-Type
      - Authorization
      - Cookie
    allow-credentials: true
