version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb_new
    ports:
      - "27017:27017"  # Maps MongoDB port to the host for local access
    environment:
      MONGO_URI: mongodb://mongodb_new:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network  # Connects MongoDB to the custom network

  user-service:
    build:
      context: user-service  # Path to your microservice's Dockerfile
    container_name: user-service
    ports:
      - "8080:8080"  # Maps your microservice port to the host
    environment:
      MONGO_URI: mongodb://mongodb:27017  # Use MongoDB container name as the host
      JWT_SECRET:
      REFRESH_TOKEN_SECRET:
    depends_on:
      - mongodb  # Ensures MongoDB starts before the microservice
    networks:
      - my_network  # Connects the microservice to the custom network

networks:
  my_network:
    driver: bridge

volumes:
  mongo_data:
