kumuluzee:
  server:
    http:
      port: 8084
    context-path: /
  logs:
    level: INFO
  dev:
    scan-interval: 5
  datasource:
    mongodb:
      connectionString: ${MONGO_URI}
      database: "financeApp"

  cors:
    enabled: true
    allow-origins:
      - http://localhost:4200
    allow-methods:
      - GET
      - POST
      - PUT
      - DELETE
    allow-headers:
      - Content-Type
      - Authorization
    allow-credentials: true
