apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-service
  labels:
    app: budget-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: budget-service
  template:
    metadata:
      labels:
        app: budget-service
    spec:
      containers:
      - name: budget-service
        image: svitdocker123/backend-budget-service:latest
        envForm:
        - secretRef:
            name: backend-secrets
        ports:
        - containerPort: 8083
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"