apiVersion: v1
kind: Service
metadata:
  name: debt-tracking-service
spec:
  selector:
    app: debt-tracking-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8086
