apiVersion: v1
kind: Service
metadata:
  name: investment-service
spec:
  selector:
    app: investment-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
      nodePort: 30005
  