apiVersion: apps/v1
kind: Deployment
metadata:
  name: investment-service
  labels:
    app: investment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: investment-service
  template:
    metadata:
      labels:
        app: investment-service
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: investment-service
        image: svitdocker123/backend-investment-service:latest
        envFrom:
        - secretRef:
            name: backend-secrets
        ports:
        - containerPort: 8085
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: "/investments/health"
            port: 8085
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: "/investments/health"
            port: 8085
          initialDelaySeconds: 20
          periodSeconds: 10