apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: mongodb
        image: svitdocker123/mongodb_new:latest
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        envFrom:
        - secretRef:
            name: backend-secrets
        readinessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "db.runCommand({ ping: 1 })"
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - "db.runCommand({ ping: 1 })"
          initialDelaySeconds: 20
          periodSeconds: 10
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-pvc