apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    worker_processes 1;

    events {
        worker_connections 1024;
    }

    http {
        upstream user_service {
            server user-service:80;
        }
        upstream savings_service {
            server savings-goal-service:80;
        }
        upstream investment_service {
            server investment-service:80;
        }
        upstream transaction_service {
            server transaction-service:80;
        }
        upstream debts_service {
            server debt-tracking-service:80;
        }
        upstream budget_service {
            server budget-service:80;
        }

        server {
            listen 80;


          location /auth {
              add_header Access-Control-Allow-Origin 'http://localhost:4200' always;
              add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS' always;
              add_header Access-Control-Allow-Headers 'Authorization, Content-Type, X-Requested-With, Cookie' always;
              add_header Access-Control-Allow-Credentials 'true' always;

              # Handle preflight (OPTIONS) requests
              if ($request_method = OPTIONS) {
                  add_header Access-Control-Allow-Origin 'http://localhost:4200' always;
                  add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS' always;
                  add_header Access-Control-Allow-Headers 'Authorization, Content-Type, X-Requested-With, Cookie' always;
                  add_header Access-Control-Allow-Credentials 'true' always;
                  add_header Content-Length 0;
                  add_header Content-Type text/plain;
                  return 204;
              }
              proxy_pass http://user_service;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          }

            location /users {
                add_header Access-Control-Allow-Origin 'http://localhost:4200' always;
                add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS' always;
                add_header Access-Control-Allow-Headers 'Authorization, Content-Type, X-Requested-With, Cookie' always;
                add_header Access-Control-Allow-Credentials 'true' always;

                # Handle preflight (OPTIONS) requests
                if ($request_method = OPTIONS) {
                    add_header Access-Control-Allow-Origin 'http://localhost:4200' always;
                    add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS' always;
                    add_header Access-Control-Allow-Headers 'Authorization, Content-Type, X-Requested-With, Cookie' always;
                    add_header Access-Control-Allow-Credentials 'true' always;
                    add_header Content-Length 0;
                    add_header Content-Type text/plain;
                    return 204;
                }
                proxy_pass http://user_service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;


            }

            location /savings-goals {
              add_header Access-Control-Allow-Origin 'http://localhost:4200' always;
                  add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS' always;
                  add_header Access-Control-Allow-Headers 'Authorization, Content-Type, X-Requested-With, Cookie' always;
                  add_header Access-Control-Allow-Credentials 'true' always;

                  # Handle preflight (OPTIONS) requests
                  if ($request_method = OPTIONS) {
                      add_header Access-Control-Allow-Origin 'http://localhost:4200' always;
                      add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS' always;
                      add_header Access-Control-Allow-Headers 'Authorization, Content-Type, X-Requested-With, Cookie' always;
                      add_header Access-Control-Allow-Credentials 'true' always;
                      add_header Content-Length 0;
                      add_header Content-Type text/plain;
                      return 204;
                  }
                proxy_pass http://savings_service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;


            }
            location /investments {
              add_header Access-Control-Allow-Origin 'http://localhost:4200' always;
              add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS' always;
              add_header Access-Control-Allow-Headers 'Authorization, Content-Type, X-Requested-With, Cookie' always;
              add_header Access-Control-Allow-Credentials 'true' always;

              # Handle preflight (OPTIONS) requests
              if ($request_method = OPTIONS) {
                  add_header Access-Control-Allow-Origin 'http://localhost:4200' always;
                  add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS' always;
                  add_header Access-Control-Allow-Headers 'Authorization, Content-Type, X-Requested-With, Cookie' always;
                  add_header Access-Control-Allow-Credentials 'true' always;
                  add_header Content-Length 0;
                  add_header Content-Type text/plain;
                  return 204;
              }
                proxy_pass http://investment_service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            }
            location /transactions {
              add_header Access-Control-Allow-Origin 'http://localhost:4200' always;
              add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS' always;
              add_header Access-Control-Allow-Headers 'Authorization, Content-Type, X-Requested-With, Cookie' always;
              add_header Access-Control-Allow-Credentials 'true' always;

              # Handle preflight (OPTIONS) requests
              if ($request_method = OPTIONS) {
                  add_header Access-Control-Allow-Origin 'http://localhost:4200' always;
                  add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS' always;
                  add_header Access-Control-Allow-Headers 'Authorization, Content-Type, X-Requested-With, Cookie' always;
                  add_header Access-Control-Allow-Credentials 'true' always;
                  add_header Content-Length 0;
                  add_header Content-Type text/plain;
                  return 204;
              }
                proxy_pass http://transaction_service;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;


            }

            location /debts {
              add_header Access-Control-Allow-Origin 'http://localhost:4200' always;
              add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS' always;
              add_header Access-Control-Allow-Headers 'Authorization, Content-Type, X-Requested-With, Cookie' always;
              add_header Access-Control-Allow-Credentials 'true' always;

              # Handle preflight (OPTIONS) requests
              if ($request_method = OPTIONS) {
                  add_header Access-Control-Allow-Origin 'http://localhost:4200' always;
                  add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS' always;
                  add_header Access-Control-Allow-Headers 'Authorization, Content-Type, X-Requested-With, Cookie' always;
                  add_header Access-Control-Allow-Credentials 'true' always;
                  add_header Content-Length 0;
                  add_header Content-Type text/plain;
                  return 204;
              }
              proxy_pass http://debts_service;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          }

          location /budget {
              add_header Access-Control-Allow-Origin 'http://localhost:4200' always;
              add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS' always;
              add_header Access-Control-Allow-Headers 'Authorization, Content-Type, X-Requested-With, Cookie' always;
              add_header Access-Control-Allow-Credentials 'true' always;

              # Handle preflight (OPTIONS) requests
              if ($request_method = OPTIONS) {
                  add_header Access-Control-Allow-Origin 'http://localhost:4200' always;
                  add_header Access-Control-Allow-Methods 'GET, POST, PUT, DELETE, OPTIONS' always;
                  add_header Access-Control-Allow-Headers 'Authorization, Content-Type, X-Requested-With, Cookie' always;
                  add_header Access-Control-Allow-Credentials 'true' always;
                  add_header Content-Length 0;
                  add_header Content-Type text/plain;
                  return 204;
              }
              proxy_pass http://budget_service;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

          }
        }
    }

