apiVersion: v1
kind: Service
metadata:
  name: savings-goal-service
spec:
  selector:
    app: savings-goal-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084