apiVersion: apps/v1
kind: Deployment
metadata:
  name: savings-goal-service
  labels:
    app: savings-goal-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: savings-goal-service
  template:
    metadata:
      labels:
        app: savings-goal-service
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: savings-goal-service
        image: svitdocker123/backend-savings-goal-service:latest
        envFrom:
        - secretRef:
            name: backend-secrets
        ports:
        - containerPort: 8084
        readinessProbe:
          httpGet:
            path: /savings-goals/health
            port: 8084
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /savings-goals/health
            port: 8084
          initialDelaySeconds: 20
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"