apiVersion: v1
kind: Service
metadata:
  name: transaction-service
spec:
  selector:
    app: transaction-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  