apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
      - name: user-service
        image: svitdocker123/user-service-prod:latest
        envFrom:
        - secretRef:
            name: backend-secrets
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /auth/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /auth/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"