kumuluzee:
  server:
    http:
      port: 8083
    context-path: /
  logs:
    level: INFO
  dev:
    scan-interval: 5
  datasource:
    mongodb:
      connectionString: ${MONGO_URI}
      database: "financeApp"