kumuluzee:
  server:
    http:
      port: 8086
    context-path: /
  logs:
    level: DEBUG
  dev:
    scan-interval: 5
  datasource:
    mongodb:
      connectionString: ${MONGO_URI}
      database: "financeApp"
  openapi:
    enabled: true
    servers:
      - url: http://localhost:8086
    info:
      title: "API Documentation"
      version: "1.0.0"
      description: "Opis API-ja za investicijsko mikrostoritev"
  swagger-ui:
    enabled: true
    path: /swagger-ui


  cors:
    enabled: true
    allow-origins:
      - http://localhost:4200
    allow-methods:
      - GET
      - POST
      - PUT
      - DELETE
    allow-headers:
      - Content-Type
      - Authorization
      - Cookie
    allow-credentials: true
